// Generated by gir (https://github.com/gtk-rs/gir @ 5223ce91b97a)
// from ../.. (@ 473544cea981+)
// from ../../gir-files (@ 473544cea981)
// DO NOT EDIT

pub fn version() -> &'static str {
{
        "1"
    }
}
