# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate pango

Name:           rust-pango0.18
Version:        0.18.3
Release:        %autorelease
Summary:        Rust bindings for the Pango library

License:        MIT
URL:            https://crates.io/crates/pango
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for the Pango library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_42-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_42-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_42" feature of the "%{crate}" crate.

%files       -n %{name}+v1_42-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_44-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_44-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_44" feature of the "%{crate}" crate.

%files       -n %{name}+v1_44-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_46-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_46-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_46" feature of the "%{crate}" crate.

%files       -n %{name}+v1_46-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_48-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_48-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_48" feature of the "%{crate}" crate.

%files       -n %{name}+v1_48-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_50-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_50-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_50" feature of the "%{crate}" crate.

%files       -n %{name}+v1_50-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_52-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_52-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_52" feature of the "%{crate}" crate.

%files       -n %{name}+v1_52-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
