stages:
 - build
 - test+docs
 - deploy

image: debian:trixie

default:
  # Protect CI infra from rogue jobs
  timeout: 15 minutes
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  DEPS: |
    git build-essential ca-certificates meson curl rustup xmlstarlet
  GIT_SUBMODULE_STRATEGY: recursive
  RUST_VERSION: stable

.common_before_script: &common_before_script
  before_script:
    - apt update
    - apt install -y --no-install-recommends eatmydata
    - eatmydata apt install -y --no-install-recommends $DEPS
    - rustup default $RUST_VERSION
    - git submodule update --checkout
    - meson subprojects download phosh
    - if [ -n "$UPSTREAM_BRANCH" ]; then cd subprojects/phosh && git fetch origin "$UPSTREAM_BRANCH" && git checkout FETCH_HEAD && cd -; fi
    - cd subprojects/phosh && eatmydata apt -y --no-install-recommends build-dep . && cd -

build:
  stage: build
  <<: *common_before_script
  script:
    # Build phosh
    - meson setup _build
    - meson compile -C _build
    - meson install -C _build
    # Build gir
    - cd gir && cargo build && cd -
    # Rebuild bindings
    - make

build-doc:
  stage: test+docs
  needs: []
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    RUSTFLAGS: --cfg docsrs
    RUST_VERSION: nightly
  <<: *common_before_script
  script:
    - ./build-doc.sh
    - mv target/doc/ docs
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  needs: [ build-doc ]
  script:
    - mkdir -p public/git
    - mv docs public/git/docs
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
