# https://packit.dev/docs/configuration/
specfile_path: phrog.spec
files_to_sync:
  - phrog.spec
  - .packit.yaml
upstream_package_name: phrog
downstream_package_name: phrog
jobs:
  # Build PRs
  - job: copr_build
    manual_trigger: true
    trigger: pull_request
    additional_repos:
      - copr://samcday/phosh-nightly
      - copr://samcday/phrog-nightly
    targets:
      fedora-41-aarch64: &opts
        without_opts:
          - vendor
      fedora-41-x86_64: *opts
      fedora-rawhide-aarch64: *opts
      fedora-rawhide-x86_64: *opts

  # Build main commits in samcday/phrog-nightly COPR
  - job: copr_build
    trigger: commit
    branch: main
    owner: samcday
    project: phrog-nightly
    additional_repos:
      - copr://samcday/phosh-nightly

  # Build tagged releases in samcday/phrog COPR
  - job: copr_build
    trigger: release
    enable_net: true
    owner: samcday
    project: phrog
