# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate glib

Name:           rust-glib0.18
Version:        0.18.5
Release:        %autorelease
Summary:        Rust bindings for the GLib library

License:        MIT
URL:            https://crates.io/crates/glib
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop unused, benchmark-only criterion dev-dependency
Patch:          glib-fix-metadata.diff
# * backport upstreamed patch to fix UB in VariantStr::impl_get:
#   https://github.com/gtk-rs/gtk-rs-core/pull/1343
Patch:          0001-fix-UB-in-VariantStrIter-impl_get.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for the GLib library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compiletests-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compiletests-devel %{_description}

This package contains library source intended for building other packages which
use the "compiletests" feature of the "%{crate}" crate.

%files       -n %{name}+compiletests-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gio-devel %{_description}

This package contains library source intended for building other packages which
use the "gio" feature of the "%{crate}" crate.

%files       -n %{name}+gio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gio_ffi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gio_ffi-devel %{_description}

This package contains library source intended for building other packages which
use the "gio_ffi" feature of the "%{crate}" crate.

%files       -n %{name}+gio_ffi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-devel %{_description}

This package contains library source intended for building other packages which
use the "log" feature of the "%{crate}" crate.

%files       -n %{name}+log-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log_macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log_macros-devel %{_description}

This package contains library source intended for building other packages which
use the "log_macros" feature of the "%{crate}" crate.

%files       -n %{name}+log_macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rs-log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rs-log-devel %{_description}

This package contains library source intended for building other packages which
use the "rs-log" feature of the "%{crate}" crate.

%files       -n %{name}+rs-log-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_58-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_58-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_58" feature of the "%{crate}" crate.

%files       -n %{name}+v2_58-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_60-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_60-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_60" feature of the "%{crate}" crate.

%files       -n %{name}+v2_60-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_62-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_62-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_62" feature of the "%{crate}" crate.

%files       -n %{name}+v2_62-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_64-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_64" feature of the "%{crate}" crate.

%files       -n %{name}+v2_64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_66-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_66-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_66" feature of the "%{crate}" crate.

%files       -n %{name}+v2_66-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_68-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_68-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_68" feature of the "%{crate}" crate.

%files       -n %{name}+v2_68-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_70-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_70-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_70" feature of the "%{crate}" crate.

%files       -n %{name}+v2_70-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_72-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_72-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_72" feature of the "%{crate}" crate.

%files       -n %{name}+v2_72-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_74-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_74-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_74" feature of the "%{crate}" crate.

%files       -n %{name}+v2_74-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_76-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_76-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_76" feature of the "%{crate}" crate.

%files       -n %{name}+v2_76-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_78-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_78-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_78" feature of the "%{crate}" crate.

%files       -n %{name}+v2_78-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip a test that crashes when built with recent Rust
# * skip a test that only works when run in-tree
%cargo_test -- -- --exact --skip collections::strv::test::test_into_strv --skip structured_log
%endif

%changelog
%autochangelog
