// Generated by gir (https://github.com/gtk-rs/gir @ 5223ce91b97a)
// from ../.. (@ b2737e839213+)
// from ../../gir-files (@ b2737e839213)
// DO NOT EDIT

pub fn version() -> &'static str {
{
        "1"
    }
}
