// Generated by gir (https://github.com/gtk-rs/gir @ 5223ce91b97a)
// from ../.. (@ 357ed151297c+)
// from ../../gir-files (@ 357ed151297c)
// DO NOT EDIT

pub fn version() -> &'static str {
{
        "1"
    }
}
