// Generated by gir (https://github.com/gtk-rs/gir @ 5223ce91b97a)
// from ../.. (@ 197bc206ff19+)
// from ../../gir-files (@ 197bc206ff19)
// DO NOT EDIT

pub fn version() -> &'static str {
{
        "1"
    }
}
