// Generated by gir (https://github.com/gtk-rs/gir @ 1ebe20c349d3)
// from ../.. (@ e422c99fc7c1+)
// from ../../gir-files (@ c775e2158c4c)
// DO NOT EDIT

#[cfg(not(docsrs))]
use std::process;

#[cfg(docsrs)]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(docsrs))]
fn main() {
    if let Err(s) = system_deps::Config::new()
        .add_build_internal("libphosh_0", |_lib, _version| {
            system_deps::Library::from_internal_pkg_config(std::env::var("LIBPHOSH_PC_PATH").unwrap(), "libphosh-0", "0.39")
        })
        .probe()
    {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
