[package]
name = "libphosh-sys"
version = "0.0.7"
edition = "2021"
build = "build.rs"
authors = ["Guido Günther <agx@sigxcpu.org>"]
categories = ["api-bindings", "gui"]
keywords = ["phosh", "gnome"]
description = "FFI bindings for libphosh"
license = "MIT"

[package.metadata.system-deps.libphosh_0_45]
name = "libphosh-0.45"
version = "0.45"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true

[lib]
name = "phosh_sys"

[dependencies]
libc = "0.2"

[dependencies.gdk_sys]
package = "gdk4-sys"
version = "0.11"

[dependencies.gio-sys]
version = "0.22"

[dependencies.glib-sys]
version = "0.22"

[dependencies.gobject-sys]
version = "0.22"

[dependencies.gtk_sys]
package = "gtk4-sys"
version = "0.11"

[build-dependencies]
pkg-config = "0.3.30"
system-deps = "7"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
static = []
