[options]
work_mode = "sys"
library = "Phosh"
version = "0"
girs_directories = ["../../gir-files", "../../"]
min_cfg_version = "1"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Gtk",
   "Gdk",
]

ignore = [
    "Phosh.DBusScreenshot",
    "Phosh.DBusScreenshotIface",
    "Phosh.DBusScreenshotProxy",
    "Phosh.DBusScreenshotSkeleton",
]

[[object]]
name = "Phosh.WallClock"
status = "generate"
  [[object.function]]
  # We don't want to bother with libgnome-desktop
  name = "string_for_datetime"
  ignore = true
