# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate libphosh

Name:           rust-libphosh
Version:        0.0.7
Release:        %autorelease
Summary:        Rust bindings for libphosh

License:        MIT
URL:            https://crates.io/crates/libphosh
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for libphosh.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v2_10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v2_10-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v2_10" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v2_10-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v2_12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v2_12-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v2_12" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v2_12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v2_18-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v2_18-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v2_18" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v2_18-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v2_20-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v2_20-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v2_20" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v2_20-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v2_4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v2_4-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v2_4" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v2_4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v2_6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v2_6-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v2_6" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v2_6-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v3-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v3" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v3_12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v3_12-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v3_12" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v3_12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v3_14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v3_14-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v3_14" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v3_14-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v3_20-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v3_20-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v3_20" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v3_20-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v3_4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v3_4-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v3_4" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v3_4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk_v3_8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk_v3_8-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk_v3_8" feature of the "%{crate}" crate.

%files       -n %{name}+gtk_v3_8-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v3_12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v3_12-devel %{_description}

This package contains library source intended for building other packages which
use the "v3_12" feature of the "%{crate}" crate.

%files       -n %{name}+v3_12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v3_14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v3_14-devel %{_description}

This package contains library source intended for building other packages which
use the "v3_14" feature of the "%{crate}" crate.

%files       -n %{name}+v3_14-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
