[package]
name = "libphosh"
version = "0.0.7"
authors = ["Guido Günther <agx@sigxcpu.org>"]
edition = "2021"
readme = "../README.md"
homepage = "https://gitlab.gnome.org/World/Phosh/libphosh-rs"
description = "Rust bindings for libphosh"
license = "MIT"
repository = "https://gitlab.gnome.org/World/Phosh/libphosh-rs.git"
categories = ["api-bindings"]
keywords = ["phosh", "gnome"]

[lib]
name = "libphosh"

[features]
default = []
gtk_v4_10 = []
gtk_v4_12 = ["gtk_v4_10"]
gtk_v4_14 = ["gtk_v4_12"]
gtk_v4_16 = ["gtk_v4_14"]
gtk_v4_18 = ["gtk_v4_16"]
gtk_v4_20 = ["gtk_v4_18"]
gtk_v4_22 = ["gtk_v4_20"]
static = ["ffi/static"]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
libc = '0.2'

[dependencies.gdk]
package = "gdk4"
version = "0.11"

[dependencies.gio]
version = "0.22"
features = [ "v2_70" ]

[dependencies.glib]
version = "0.22"
features = [ "v2_66" ]

[dependencies.gtk]
package = "gtk4"
version = "0.11"

[dependencies.ffi]
package = "libphosh-sys"
path = './sys'
version = "0.0.7"
