// Generated by gir (https://github.com/gtk-rs/gir @ 601c9bb7f8f4)
// from ../.. (@ e6d4e95f67c0+)
// from ../../gir-files (@ d530241ca19b)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((guint) PHOSH_LAYER_SURFACE_ANCHOR_BOTTOM);
    PRINT_CONSTANT((guint) PHOSH_LAYER_SURFACE_ANCHOR_LEFT);
    PRINT_CONSTANT((guint) PHOSH_LAYER_SURFACE_ANCHOR_NONE);
    PRINT_CONSTANT((guint) PHOSH_LAYER_SURFACE_ANCHOR_RIGHT);
    PRINT_CONSTANT((guint) PHOSH_LAYER_SURFACE_ANCHOR_TOP);
    PRINT_CONSTANT((gint) PHOSH_LAYER_SURFACE_LAYER_BACKGROUND);
    PRINT_CONSTANT((gint) PHOSH_LAYER_SURFACE_LAYER_BOTTOM);
    PRINT_CONSTANT((gint) PHOSH_LAYER_SURFACE_LAYER_OVERLAY);
    PRINT_CONSTANT((gint) PHOSH_LAYER_SURFACE_LAYER_TOP);
    PRINT_CONSTANT((gint) PHOSH_LOCKSCREEN_PAGE_EXTRA);
    PRINT_CONSTANT((gint) PHOSH_LOCKSCREEN_PAGE_INFO);
    PRINT_CONSTANT((gint) PHOSH_LOCKSCREEN_PAGE_UNLOCK);
    return 0;
}
