// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PhoshLayerSurface", sizeof(PhoshLayerSurface), alignof(PhoshLayerSurface));
    printf("%s;%zu;%zu\n", "PhoshLayerSurfaceClass", sizeof(PhoshLayerSurfaceClass), alignof(PhoshLayerSurfaceClass));
    printf("%s;%zu;%zu\n", "PhoshLockscreen", sizeof(PhoshLockscreen), alignof(PhoshLockscreen));
    printf("%s;%zu;%zu\n", "PhoshLockscreenClass", sizeof(PhoshLockscreenClass), alignof(PhoshLockscreenClass));
    printf("%s;%zu;%zu\n", "PhoshLockscreenPage", sizeof(PhoshLockscreenPage), alignof(PhoshLockscreenPage));
    printf("%s;%zu;%zu\n", "PhoshShellClass", sizeof(PhoshShellClass), alignof(PhoshShellClass));
    return 0;
}
