# Generated by rust2rpm 27
# * tests are broken: https://github.com/gtk-rs/gtk-rs-core/issues/64
%bcond check 0
%global debug_package %{nil}

%global crate atk-sys

Name:           rust-atk-sys
Version:        0.18.2
Release:        %autorelease
Summary:        FFI bindings to libatk-1

License:        MIT
URL:            https://crates.io/crates/atk-sys
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(atk) >= 2.28

%global _description %{expand:
FFI bindings to libatk-1.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(atk) >= 2.28
# https://fedoraproject.org/wiki/Changes/Deprecate_gtk3-rs
Provides:       deprecated()

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_30-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(atk) >= 2.30

%description -n %{name}+v2_30-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_30" feature of the "%{crate}" crate.

%files       -n %{name}+v2_30-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_32-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(atk) >= 2.32

%description -n %{name}+v2_32-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_32" feature of the "%{crate}" crate.

%files       -n %{name}+v2_32-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_34-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(atk) >= 2.34

%description -n %{name}+v2_34-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_34" feature of the "%{crate}" crate.

%files       -n %{name}+v2_34-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_38-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(atk) >= 2.38

%description -n %{name}+v2_38-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_38" feature of the "%{crate}" crate.

%files       -n %{name}+v2_38-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_46-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(atk) >= 2.46

%description -n %{name}+v2_46-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_46" feature of the "%{crate}" crate.

%files       -n %{name}+v2_46-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
