# Generated by rust2rpm 27
# * tests require a running display server
%bcond check 0
%global debug_package %{nil}

%global crate libhandy

Name:           rust-libhandy
Version:        0.11.1
Release:        %autorelease
Summary:        Rust bindings for libhandy

License:        LGPL-2.1-only
URL:            https://crates.io/crates/libhandy
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for libhandy.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
# https://fedoraproject.org/wiki/Changes/Deprecate_gtk3-rs
Provides:       deprecated()

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_0-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_0-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_0" feature of the "%{crate}" crate.

%files       -n %{name}+v1_0-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_2-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_2" feature of the "%{crate}" crate.

%files       -n %{name}+v1_2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_4-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_4" feature of the "%{crate}" crate.

%files       -n %{name}+v1_4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_6-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_6" feature of the "%{crate}" crate.

%files       -n %{name}+v1_6-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
