# Generated by rust2rpm 26
# * missing dev-dependency: float_eq
%bcond_with check
%global debug_package %{nil}

%global crate cairo-rs

Name:           rust-cairo-rs0.18
Version:        0.18.5
Release:        %autorelease
Summary:        Rust bindings for the Cairo library

License:        MIT
URL:            https://crates.io/crates/cairo-rs
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for the Cairo library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+freetype-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+freetype-devel %{_description}

This package contains library source intended for building other packages which
use the "freetype" feature of the "%{crate}" crate.

%files       -n %{name}+freetype-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+freetype-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+freetype-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "freetype-rs" feature of the "%{crate}" crate.

%files       -n %{name}+freetype-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glib-devel %{_description}

This package contains library source intended for building other packages which
use the "glib" feature of the "%{crate}" crate.

%files       -n %{name}+glib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pdf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pdf-devel %{_description}

This package contains library source intended for building other packages which
use the "pdf" feature of the "%{crate}" crate.

%files       -n %{name}+pdf-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+png-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+png-devel %{_description}

This package contains library source intended for building other packages which
use the "png" feature of the "%{crate}" crate.

%files       -n %{name}+png-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ps-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ps-devel %{_description}

This package contains library source intended for building other packages which
use the "ps" feature of the "%{crate}" crate.

%files       -n %{name}+ps-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+script-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+script-devel %{_description}

This package contains library source intended for building other packages which
use the "script" feature of the "%{crate}" crate.

%files       -n %{name}+script-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+svg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+svg-devel %{_description}

This package contains library source intended for building other packages which
use the "svg" feature of the "%{crate}" crate.

%files       -n %{name}+svg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_glib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_glib-devel %{_description}

This package contains library source intended for building other packages which
use the "use_glib" feature of the "%{crate}" crate.

%files       -n %{name}+use_glib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_16-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_16-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_16" feature of the "%{crate}" crate.

%files       -n %{name}+v1_16-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v1_18-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_18-devel %{_description}

This package contains library source intended for building other packages which
use the "v1_18" feature of the "%{crate}" crate.

%files       -n %{name}+v1_18-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xcb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xcb-devel %{_description}

This package contains library source intended for building other packages which
use the "xcb" feature of the "%{crate}" crate.

%files       -n %{name}+xcb-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xlib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xlib-devel %{_description}

This package contains library source intended for building other packages which
use the "xlib" feature of the "%{crate}" crate.

%files       -n %{name}+xlib-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
