// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "PhoshKeypad")]
    pub struct Keypad(Object<ffi::PhoshKeypad, ffi::PhoshKeypadClass>) @extends gtk::Grid, gtk::Container, gtk::Widget;

    match fn {
        type_ => || ffi::phosh_keypad_get_type(),
    }
}

impl Keypad {
    #[doc(alias = "phosh_keypad_new")]
    pub fn new() -> Keypad {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_none(ffi::phosh_keypad_new()).unsafe_cast()
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`Keypad`] objects.
            ///
            /// This method returns an instance of [`KeypadBuilder`](crate::builders::KeypadBuilder) which can be used to create [`Keypad`] objects.
            pub fn builder() -> KeypadBuilder {
                KeypadBuilder::new()
            }
        

    #[doc(alias = "phosh_keypad_distribute")]
    pub fn distribute(&self) {
        unsafe {
            ffi::phosh_keypad_distribute(self.to_glib_none().0);
        }
    }

    #[doc(alias = "phosh_keypad_get_end_action")]
    #[doc(alias = "get_end_action")]
    pub fn end_action(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::phosh_keypad_get_end_action(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "phosh_keypad_get_entry")]
    //#[doc(alias = "get_entry")]
    //pub fn entry(&self) -> /*Ignored*/gtk::Entry {
    //    unsafe { TODO: call ffi:phosh_keypad_get_entry() }
    //}

    #[doc(alias = "phosh_keypad_get_shuffle")]
    #[doc(alias = "get_shuffle")]
    pub fn is_shuffle(&self) -> bool {
        unsafe {
            from_glib(ffi::phosh_keypad_get_shuffle(self.to_glib_none().0))
        }
    }

    #[doc(alias = "phosh_keypad_get_start_action")]
    #[doc(alias = "get_start_action")]
    pub fn start_action(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::phosh_keypad_get_start_action(self.to_glib_none().0))
        }
    }

    #[doc(alias = "phosh_keypad_set_end_action")]
    pub fn set_end_action(&self, end_action: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::phosh_keypad_set_end_action(self.to_glib_none().0, end_action.map(|p| p.as_ref()).to_glib_none().0);
        }
    }

    //#[doc(alias = "phosh_keypad_set_entry")]
    //pub fn set_entry(&self, entry: /*Ignored*/Option<&gtk::Entry>) {
    //    unsafe { TODO: call ffi:phosh_keypad_set_entry() }
    //}

    #[doc(alias = "phosh_keypad_set_shuffle")]
    pub fn set_shuffle(&self, shuffle: bool) {
        unsafe {
            ffi::phosh_keypad_set_shuffle(self.to_glib_none().0, shuffle.into_glib());
        }
    }

    #[doc(alias = "phosh_keypad_set_start_action")]
    pub fn set_start_action(&self, start_action: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::phosh_keypad_set_start_action(self.to_glib_none().0, start_action.map(|p| p.as_ref()).to_glib_none().0);
        }
    }

    #[doc(alias = "end-action")]
    pub fn connect_end_action_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_end_action_trampoline<F: Fn(&Keypad) + 'static>(this: *mut ffi::PhoshKeypad, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::end-action\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(notify_end_action_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "entry")]
    pub fn connect_entry_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_entry_trampoline<F: Fn(&Keypad) + 'static>(this: *mut ffi::PhoshKeypad, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::entry\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(notify_entry_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "shuffle")]
    pub fn connect_shuffle_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_shuffle_trampoline<F: Fn(&Keypad) + 'static>(this: *mut ffi::PhoshKeypad, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::shuffle\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(notify_shuffle_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "start-action")]
    pub fn connect_start_action_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_start_action_trampoline<F: Fn(&Keypad) + 'static>(this: *mut ffi::PhoshKeypad, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::start-action\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(notify_start_action_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl Default for Keypad {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`Keypad`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct KeypadBuilder {
            builder: glib::object::ObjectBuilder<'static, Keypad>,
        }

        impl KeypadBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn end_action(self, end_action: &impl IsA<gtk::Widget>) -> Self {
                            Self { builder: self.builder.property("end-action", end_action.clone().upcast()), }
                        }

                            //pub fn entry(self, entry: &impl IsA</*Ignored*/gtk::Entry>) -> Self {
                        //    Self { builder: self.builder.property("entry", entry.clone().upcast()), }
                        //}

                            pub fn shuffle(self, shuffle: bool) -> Self {
                            Self { builder: self.builder.property("shuffle", shuffle), }
                        }

                            pub fn start_action(self, start_action: &impl IsA<gtk::Widget>) -> Self {
                            Self { builder: self.builder.property("start-action", start_action.clone().upcast()), }
                        }

                            pub fn baseline_row(self, baseline_row: i32) -> Self {
                            Self { builder: self.builder.property("baseline-row", baseline_row), }
                        }

                            pub fn column_homogeneous(self, column_homogeneous: bool) -> Self {
                            Self { builder: self.builder.property("column-homogeneous", column_homogeneous), }
                        }

                            pub fn column_spacing(self, column_spacing: i32) -> Self {
                            Self { builder: self.builder.property("column-spacing", column_spacing), }
                        }

                            pub fn row_homogeneous(self, row_homogeneous: bool) -> Self {
                            Self { builder: self.builder.property("row-homogeneous", row_homogeneous), }
                        }

                            pub fn row_spacing(self, row_spacing: i32) -> Self {
                            Self { builder: self.builder.property("row-spacing", row_spacing), }
                        }

                            pub fn border_width(self, border_width: u32) -> Self {
                            Self { builder: self.builder.property("border-width", border_width), }
                        }

                            pub fn child(self, child: &impl IsA<gtk::Widget>) -> Self {
                            Self { builder: self.builder.property("child", child.clone().upcast()), }
                        }

                            //pub fn resize_mode(self, resize_mode: /*Ignored*/gtk::ResizeMode) -> Self {
                        //    Self { builder: self.builder.property("resize-mode", resize_mode), }
                        //}

                            pub fn app_paintable(self, app_paintable: bool) -> Self {
                            Self { builder: self.builder.property("app-paintable", app_paintable), }
                        }

                            pub fn can_default(self, can_default: bool) -> Self {
                            Self { builder: self.builder.property("can-default", can_default), }
                        }

                            pub fn can_focus(self, can_focus: bool) -> Self {
                            Self { builder: self.builder.property("can-focus", can_focus), }
                        }

                            #[cfg(feature = "gtk_v2_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v2_18")))]
    #[cfg_attr(feature = "v3_14", deprecated = "Since 3.14")]
    pub fn double_buffered(self, double_buffered: bool) -> Self {
                            Self { builder: self.builder.property("double-buffered", double_buffered), }
                        }

                            //pub fn events(self, events: /*Ignored*/gdk::EventMask) -> Self {
                        //    Self { builder: self.builder.property("events", events), }
                        //}

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn expand(self, expand: bool) -> Self {
                            Self { builder: self.builder.property("expand", expand), }
                        }

                            #[cfg(feature = "gtk_v3_20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3_20")))]
    pub fn focus_on_click(self, focus_on_click: bool) -> Self {
                            Self { builder: self.builder.property("focus-on-click", focus_on_click), }
                        }

                        //    #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    //pub fn halign(self, halign: /*Ignored*/gtk::Align) -> Self {
                        //    Self { builder: self.builder.property("halign", halign), }
                        //}

                            pub fn has_default(self, has_default: bool) -> Self {
                            Self { builder: self.builder.property("has-default", has_default), }
                        }

                            pub fn has_focus(self, has_focus: bool) -> Self {
                            Self { builder: self.builder.property("has-focus", has_focus), }
                        }

                            #[cfg(feature = "gtk_v2_12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v2_12")))]
    pub fn has_tooltip(self, has_tooltip: bool) -> Self {
                            Self { builder: self.builder.property("has-tooltip", has_tooltip), }
                        }

                            pub fn height_request(self, height_request: i32) -> Self {
                            Self { builder: self.builder.property("height-request", height_request), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn hexpand(self, hexpand: bool) -> Self {
                            Self { builder: self.builder.property("hexpand", hexpand), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn hexpand_set(self, hexpand_set: bool) -> Self {
                            Self { builder: self.builder.property("hexpand-set", hexpand_set), }
                        }

                            pub fn is_focus(self, is_focus: bool) -> Self {
                            Self { builder: self.builder.property("is-focus", is_focus), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn margin(self, margin: i32) -> Self {
                            Self { builder: self.builder.property("margin", margin), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn margin_bottom(self, margin_bottom: i32) -> Self {
                            Self { builder: self.builder.property("margin-bottom", margin_bottom), }
                        }

                            #[cfg(feature = "gtk_v3_12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3_12")))]
    pub fn margin_end(self, margin_end: i32) -> Self {
                            Self { builder: self.builder.property("margin-end", margin_end), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    #[cfg_attr(feature = "v3_12", deprecated = "Since 3.12")]
    pub fn margin_left(self, margin_left: i32) -> Self {
                            Self { builder: self.builder.property("margin-left", margin_left), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    #[cfg_attr(feature = "v3_12", deprecated = "Since 3.12")]
    pub fn margin_right(self, margin_right: i32) -> Self {
                            Self { builder: self.builder.property("margin-right", margin_right), }
                        }

                            #[cfg(feature = "gtk_v3_12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3_12")))]
    pub fn margin_start(self, margin_start: i32) -> Self {
                            Self { builder: self.builder.property("margin-start", margin_start), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn margin_top(self, margin_top: i32) -> Self {
                            Self { builder: self.builder.property("margin-top", margin_top), }
                        }

                            pub fn name(self, name: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("name", name.into()), }
                        }

                            pub fn no_show_all(self, no_show_all: bool) -> Self {
                            Self { builder: self.builder.property("no-show-all", no_show_all), }
                        }

                            #[cfg(feature = "gtk_v3_8")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3_8")))]
    pub fn opacity(self, opacity: f64) -> Self {
                            Self { builder: self.builder.property("opacity", opacity), }
                        }

                            pub fn parent(self, parent: &impl IsA<gtk::Container>) -> Self {
                            Self { builder: self.builder.property("parent", parent.clone().upcast()), }
                        }

                            pub fn receives_default(self, receives_default: bool) -> Self {
                            Self { builder: self.builder.property("receives-default", receives_default), }
                        }

                            pub fn sensitive(self, sensitive: bool) -> Self {
                            Self { builder: self.builder.property("sensitive", sensitive), }
                        }

                            //pub fn style(self, style: &impl IsA</*Ignored*/gtk::Style>) -> Self {
                        //    Self { builder: self.builder.property("style", style.clone().upcast()), }
                        //}

                            #[cfg(feature = "gtk_v2_12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v2_12")))]
    pub fn tooltip_markup(self, tooltip_markup: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("tooltip-markup", tooltip_markup.into()), }
                        }

                            #[cfg(feature = "gtk_v2_12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v2_12")))]
    pub fn tooltip_text(self, tooltip_text: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("tooltip-text", tooltip_text.into()), }
                        }

                        //    #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    //pub fn valign(self, valign: /*Ignored*/gtk::Align) -> Self {
                        //    Self { builder: self.builder.property("valign", valign), }
                        //}

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn vexpand(self, vexpand: bool) -> Self {
                            Self { builder: self.builder.property("vexpand", vexpand), }
                        }

                            #[cfg(feature = "gtk_v3")]
    #[cfg_attr(docsrs, doc(cfg(feature = "gtk_v3")))]
    pub fn vexpand_set(self, vexpand_set: bool) -> Self {
                            Self { builder: self.builder.property("vexpand-set", vexpand_set), }
                        }

                            pub fn visible(self, visible: bool) -> Self {
                            Self { builder: self.builder.property("visible", visible), }
                        }

                            pub fn width_request(self, width_request: i32) -> Self {
                            Self { builder: self.builder.property("width-request", width_request), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`Keypad`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Keypad {
    self.builder.build() }
}
