# Generated by rust2rpm 27
# * tests require a running display server
%bcond check 0
%global debug_package %{nil}

%global crate gdk

Name:           rust-gdk
Version:        0.18.2
Release:        %autorelease
Summary:        Rust bindings for the GDK 3 library

License:        MIT
URL:            https://crates.io/crates/gdk
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for the GDK 3 library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
# https://fedoraproject.org/wiki/Changes/Deprecate_gtk3-rs
Provides:       deprecated()

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unsafe-assume-initialized-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unsafe-assume-initialized-devel %{_description}

This package contains library source intended for building other packages which
use the "unsafe-assume-initialized" feature of the "%{crate}" crate.

%files       -n %{name}+unsafe-assume-initialized-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v3_24-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v3_24-devel %{_description}

This package contains library source intended for building other packages which
use the "v3_24" feature of the "%{crate}" crate.

%files       -n %{name}+v3_24-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
