# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate atk

Name:           rust-atk
Version:        0.18.2
Release:        %autorelease
Summary:        Rust bindings for the ATK library

License:        MIT
URL:            https://crates.io/crates/atk
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for the ATK library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
# https://fedoraproject.org/wiki/Changes/Deprecate_gtk3-rs
Provides:       deprecated()

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_30-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_30-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_30" feature of the "%{crate}" crate.

%files       -n %{name}+v2_30-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_32-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_32" feature of the "%{crate}" crate.

%files       -n %{name}+v2_32-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_34-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_34-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_34" feature of the "%{crate}" crate.

%files       -n %{name}+v2_34-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_38-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_38-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_38" feature of the "%{crate}" crate.

%files       -n %{name}+v2_38-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_46-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_46-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_46" feature of the "%{crate}" crate.

%files       -n %{name}+v2_46-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
