# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate gio

Name:           rust-gio0.18
Version:        0.18.4
Release:        %autorelease
Summary:        Rust bindings for the Gio library

License:        MIT
URL:            https://crates.io/crates/gio
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for the Gio library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_58-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_58-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_58" feature of the "%{crate}" crate.

%files       -n %{name}+v2_58-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_60-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_60-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_60" feature of the "%{crate}" crate.

%files       -n %{name}+v2_60-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_62-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_62-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_62" feature of the "%{crate}" crate.

%files       -n %{name}+v2_62-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_64-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_64" feature of the "%{crate}" crate.

%files       -n %{name}+v2_64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_66-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_66-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_66" feature of the "%{crate}" crate.

%files       -n %{name}+v2_66-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_68-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_68-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_68" feature of the "%{crate}" crate.

%files       -n %{name}+v2_68-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_70-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_70-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_70" feature of the "%{crate}" crate.

%files       -n %{name}+v2_70-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_72-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_72-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_72" feature of the "%{crate}" crate.

%files       -n %{name}+v2_72-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_74-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_74-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_74" feature of the "%{crate}" crate.

%files       -n %{name}+v2_74-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_76-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_76-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_76" feature of the "%{crate}" crate.

%files       -n %{name}+v2_76-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_78-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_78-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_78" feature of the "%{crate}" crate.

%files       -n %{name}+v2_78-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
