name: build-image

on:
  push:
    paths:
      - .github/workflows/build-image.yml
      - .github/Dockerfile
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .github/
          file: .github/Dockerfile
          push: true
          tags: ghcr.io/samcday/phrog-ci:${{ hashFiles('.github/Dockerfile') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
