# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate gdk-pixbuf

Name:           rust-gdk-pixbuf0.18
Version:        0.18.5
Release:        %autorelease
Summary:        Rust bindings for the GdkPixbuf library

License:        MIT
URL:            https://crates.io/crates/gdk-pixbuf
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for the GdkPixbuf library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_40-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_40-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_40" feature of the "%{crate}" crate.

%files       -n %{name}+v2_40-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_42-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_42-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_42" feature of the "%{crate}" crate.

%files       -n %{name}+v2_42-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
